api:
  dashboard: true
ping: {}

entryPoints:
  traefik:
    address: ":8080"
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
  file:
    directory: "${TRAEFIK_DYNAMIC_DIR:-/etc/traefik/dynamic}"
    watch: true
